### ISSUE TITLE
More vibrant output?

### ISSUE THREAD

**Issue by tonychandesign** [cristicretu/meshgrad#3]
hey this is awesome!  Is there anyway to make the output gradients more vibrant?  The colors are a bit washed out/pastel-y

**Comment by cristicretu** [comment]
Hey! Played around with the values and made everything more vibrant. Thanks for the heads up!
Use any version >= 0.0.11 and you should be set!
![image](https://user-images.githubusercontent.com/45521157/231172965-7343011a-1631-4656-ab08-e10d249da32e.png)
